# JWT Configuration
jwt.secret=TechCupSecretKey2024VerySecureLongKeyForJWT
jwt.expiration=36000000

# Base de datos (puedes usar H2 para pruebas)
spring.datasource.url=jdbc:h2:mem:techcupdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true